name: Print Software Versions

on:
  push:
    branches:
      - main 

jobs:
  # Робота 1: Рівень обробки даних
  PrintAppVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version

  # Робота 2: Рівень доступу даних
  PrintDBMSVersions:
    runs-on: ubuntu-latest
    
    # Ця робота (needs) почнеться тільки після успішного завершення PrintAppVersions
    needs: [PrintAppVersions]
    
    steps:
      - name: Print PostgreSQL Version
        run: psql --version
