name: Javascript Code Linter

on:
  push:
    branches:
      - main

jobs:
  JavaScriptCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install JS Linter Biome
        run: npm install --save-dev --save-exact @biomejs/biome

      - name: Validate all js-file
        run: npx @biomejs/biome check *.js
